name: Deploy to GitHub Pages

# Trigger on pushes to main branch and allow manual workflow dispatch
on:
  push:
    branches: [main]
  workflow_dispatch:

# Set permissions for the workflow
permissions:
  contents: read  # Allow reading repository contents
  pages: write    # Allow writing to GitHub Pages
  id-token: write # Allow ID token generation for deployment

jobs:
  # Build job to prepare artifacts
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
      
      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify Node.js version
          cache: 'npm'      # Enable npm caching
      
      # Detailed environment information
      - name: System and Environment Details
        run: |
          echo "Operating System:"
          cat /etc/os-release
          echo "---"
          echo "Node.js version:"
          node --version
          echo "---"
          echo "npm version:"
          npm --version
          echo "---"
          echo "Current directory:"
          pwd
          echo "---"
          echo "Directory contents:"
          ls -la
          echo "---"
          echo "Git branch:"
          git branch
      
      # Install project dependencies with verbose output
      - name: Install dependencies
        run: |
          npm install
          echo "Installed packages:"
          npm list || true
      
      # Build the project with maximum verbosity
      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          npm run build --verbose
          echo "Build exit code: $?"
      
      # Comprehensive build output
      - name: Detailed Build Output
        run: |
          echo "Root directory contents:"
          ls -la
          echo "---"
          echo "Docs directory contents:"
          ls -la docs || echo "Docs directory not found"
          echo "---"
          echo "Full directory structure:"
          find . -type d
          echo "---"
          echo "Build log files:"
          find . -name "*.log"
      
      # Upload build artifacts to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs  # Specify artifact directory

  # Deploy job to publish to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build  # Depends on successful build job
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
